### ISSUE TITLE
select network interface via used bandwith

### ISSUE THREAD

**Issue by conrad784** [lightful/xfce-hkmon#6]
Hi,
as I'm quite often switching between WiFi and Ethernet it would be neat to have a choice for selecting the default network interface between total download (like now) and the overall traffic since last update. I just hacked this part for me and it works for me. Should this be an option or is this something only I need?
If this should be an option, should this be done via and extra option "-b" or something like an extra value "NETBW"?

**Comment by lightful** [comment]
You have reason... I personally have manually selected the interface at times. So I have changed the default behaviour to do what you did. For most people this is just the network they are in at the time, and for the rest I think that it there isn't really a good heuristic for auto-selection. Adding the interfaces traffic as a kind of a summary wasn't either an option, since in some situations some devices could in fact include others.

Thanks for the idea!
